server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/projects-server-task
    username: someUser
    password: somePassword

  flyway:
    url: jdbc:postgresql://localhost:5432/projects-server-task
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

